"""add turmas turma_alunos notas

Revision ID: 697fab64fa9a
Revises: dbec855df65b
Create Date: 2026-03-18 08:43:30.193697

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '697fab64fa9a'
down_revision = 'dbec855df65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frequencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_frequencias_curso_id', 'cursos', ['curso_id'], ['id'])

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativa', sa.Integer(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    op.create_table('turmas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.Column('modalidade', sa.String(length=20), nullable=False),
        sa.Column('tipo', sa.String(length=20), nullable=False),
        sa.Column('curso_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], name='fk_turmas_curso_id'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('notas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('aluno_id', sa.Integer(), nullable=False),
        sa.Column('materia_id', sa.Integer(), nullable=False),
        sa.Column('curso_id', sa.Integer(), nullable=False),
        sa.Column('nota', sa.Float(), nullable=True),
        sa.Column('resultado', sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name='fk_notas_aluno_id'),
        sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='fk_notas_materia_id'),
        sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], name='fk_notas_curso_id'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('aluno_id', 'materia_id', 'curso_id', name='uq_notas_aluno_materia_curso')
    )
    op.create_index('ix_notas_aluno_id', 'notas', ['aluno_id'])

    op.create_table('turma_alunos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('turma_id', sa.Integer(), nullable=False),
        sa.Column('aluno_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name='fk_turma_alunos_turma_id'),
        sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name='fk_turma_alunos_aluno_id'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('turma_id', 'aluno_id', name='uq_turma_alunos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_alunos')
    op.drop_index('ix_notas_aluno_id', table_name='notas')
    op.drop_table('notas')
    op.drop_table('turmas')

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('ativa')

    with op.batch_alter_table('frequencias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_frequencias_curso_id', type_='foreignkey')
        batch_op.drop_column('curso_id')
    # ### end Alembic commands ###
