"""initial

Revision ID: dbec855df65b
Revises: 
Create Date: 2026-03-17 10:02:44.832265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbec855df65b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor_mensal', sa.Float(), nullable=True),
    sa.Column('valor_matricula', sa.Float(), nullable=True),
    sa.Column('parcelas', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('data', sa.String(length=10), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('recorrente', sa.Integer(), nullable=True),
    sa.Column('dia_vencimento', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=True),
    sa.Column('meta', sa.Integer(), nullable=True),
    sa.Column('realizado', sa.Integer(), nullable=True),
    sa.Column('matriculas', sa.Integer(), nullable=True),
    sa.Column('matriculas_venda', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mes')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('perfil', sa.String(length=40), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('data_nascimento', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.String(length=10), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_nome', sa.String(length=120), nullable=True),
    sa.Column('responsavel_cpf', sa.String(length=14), nullable=True),
    sa.Column('responsavel_telefone', sa.String(length=20), nullable=True),
    sa.Column('responsavel_parentesco', sa.String(length=40), nullable=True),
    sa.Column('senha', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteudos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('modulo', sa.String(length=60), nullable=True),
    sa.Column('arquivo', sa.String(length=300), nullable=True),
    sa.Column('data', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos_materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frequencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frequencias', schema=None) as batch_op:
        batch_op.create_index('ix_frequencias_aluno_id', ['aluno_id'], unique=False)

    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('tipo_curso', sa.String(length=60), nullable=True),
    sa.Column('data_matricula', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('valor_matricula', sa.Float(), nullable=True),
    sa.Column('valor_mensalidade', sa.Float(), nullable=True),
    sa.Column('quantidade_parcelas', sa.Integer(), nullable=True),
    sa.Column('material_didatico', sa.String(length=20), nullable=True),
    sa.Column('valor_material', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matriculas_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('mensalidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('vencimento', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('parcela_ref', sa.String(length=20), nullable=True),
    sa.Column('data_pagamento', sa.String(length=10), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=True),
    sa.Column('usuario_pagamento', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensalidades', schema=None) as batch_op:
        batch_op.create_index('ix_mensalidades_aluno_id', ['aluno_id'], unique=False)
        batch_op.create_index('ix_mensalidades_status', ['status'], unique=False)
        batch_op.create_index('ix_mensalidades_vencimento', ['vencimento'], unique=False)

    op.create_table('progresso_aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('conteudo_id', sa.Integer(), nullable=True),
    sa.Column('concluido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'conteudo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progresso_aulas')
    with op.batch_alter_table('mensalidades', schema=None) as batch_op:
        batch_op.drop_index('ix_mensalidades_vencimento')
        batch_op.drop_index('ix_mensalidades_status')
        batch_op.drop_index('ix_mensalidades_aluno_id')

    op.drop_table('mensalidades')
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriculas_aluno_id'))

    op.drop_table('matriculas')
    with op.batch_alter_table('frequencias', schema=None) as batch_op:
        batch_op.drop_index('ix_frequencias_aluno_id')

    op.drop_table('frequencias')
    op.drop_table('cursos_materias')
    op.drop_table('conteudos')
    op.drop_table('materias')
    op.drop_table('alunos')
    op.drop_table('usuarios')
    op.drop_table('relatorios')
    op.drop_table('despesas')
    op.drop_table('cursos')
    # ### end Alembic commands ###
