"""initial

Revision ID: f89023fdbe0c
Revises: 697fab64fa9a
Create Date: 2026-03-18 15:26:33.892775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89023fdbe0c'
down_revision = '697fab64fa9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conteudos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(length=300), nullable=True))

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracao', sa.String(length=60), nullable=True))

    with op.batch_alter_table('frequencias', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_frequencias_aluno_curso_data', ['aluno_id', 'curso_id', 'data'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frequencias', schema=None) as batch_op:
        batch_op.drop_constraint('uq_frequencias_aluno_curso_data', type_='unique')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_column('duracao')

    with op.batch_alter_table('conteudos', schema=None) as batch_op:
        batch_op.drop_column('video')

    # ### end Alembic commands ###
